### ISSUE TITLE
G2Export tables don't display properly 

### ISSUE THREAD

**Issue by jbutcher21** [Senzing/docker-senzing-console#55]
You get this rater than pretty grid lines ...
<E2><94><BC><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><BC><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80>
<E2><94><82> Record ID <E2><94><82> Entity Data                                  <E2><94><82> Additional Data  <E2><94><82>
<E2><94><BC><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><BC><E2><94><80><E2><94><80><E2><94><80><E2><94><80><E2><94><80>
<E2><94><82> CUSTOMERS <E2><94><82> PRIMARY: Smith Bob J                         <E2><94><82> AMOUNT: 100      <E2><94><82>
<E2><94><82> 1001      <E2><94><82> PRIMARY: Smith II Bob                        <E2><94><82> AMOUNT: 200      <E2><94><82>

**To fix it, locale to UTF-8 like this ... 
    export LC_ALL=C.UTF-8**

This should also be fixed in sshd and debug in case users try to use G2Export from any of them.

and voila ...
Entity summary for entity 1: Bob Smith II
┼───────────┼──────────────────────────────────────────────┼──────────────────┼
│ Record ID │ Entity Data                                  │ Additional Data  │
┼───────────┼──────────────────────────────────────────────┼──────────────────┼
│ CUSTOMERS │ PRIMARY: Smith B                             │ AMOUNT: 100      │
│ 1001      │ PRIMARY: Smith Bob J                         │ AMOUNT: 200      │
│ 1002      │ PRIMARY: Smith Rob E                         │ AMOUNT: 300      │
│ 1003      │ PRIMARY: Smith Robert                        │ AMOUNT: 400      │

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/docker-senzing-console/pull/56
